name: Deploy

on:
  push:
    tags:
      - '**'

env:
  CACHE_VERSION: v1

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CACHE_VERSION: ${{ secrets.CACHE_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ env.CACHE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.CACHE_VERSION }}-
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run generate
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_PUT_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_PUT_SECRET_KEY }}
        run: aws s3 cp dist/ ${{ secrets. AWS_S3_RESTHUB_BUCKET }} --recursive
